#!/bin/bash

# This command can be run by the user to clang-format everything.

PLATFORM=$(uname)
CLANGFORMAT="./scripts/${PLATFORM}/clang-format -style=file"

find format-project/io \( -name *.cpp -or -name *.h \) -print0 | xargs -n1 -0 ${CLANGFORMAT} -i

echo "format-all done"